title: Создание сайтов в Киеве
url: "http://blog-ua.tk"
permalink: /:title.html
lang: ru-UA
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-sitemap
  - jekyll-feed
